style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG

options:
  commits:
    # filters:
    #   Type:
    #     - feat
    #     - fix
    #     - perf
    #     - refactor
  commit_groups:
    sort_by: Custom
    title_order:
        - feat
        - update
        - perf
        - fix
        - refactor
        - docs
        - build
        - chore
        - ci
    title_maps:
      feat: Features âœ¨
      fix: Bug Fixes ğŸ›
      perf: Performance Improvements âš¡
      refactor: Code Refactoring â™»
      update: Updates ğŸ”„
      build: Build ğŸ‘·
      ci: Continuous Integration ğŸ”„
      chore: Other changes
      docs: Documentation ğŸ“–
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE